#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

if command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN=python3
elif command -v python >/dev/null 2>&1; then
  PYTHON_BIN=python
else
  echo "python3/python not found" >&2
  exit 1
fi

font_id() {
  "$PYTHON_BIN" - "$@" <<'PY'
import hashlib
import sys

total = 0
for path in sys.argv[1:]:
    with open(path, "rb") as f:
        total += int(hashlib.sha256(f.read()).hexdigest(), 16)

value = total % (2 ** 32) - (2 ** 31)
print(value)
PY
}

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""

echo "#define BOOKERLY_14_FONT_ID ($(font_id ./bookerly_14_regular.h ./bookerly_14_bold.h ./bookerly_14_bolditalic.h ./bookerly_14_italic.h))"
echo "#define BOOKERLY_16_FONT_ID ($(font_id ./bookerly_16_regular.h ./bookerly_16_bold.h ./bookerly_16_bolditalic.h ./bookerly_16_italic.h))"
echo "#define BOOKERLY_18_FONT_ID ($(font_id ./bookerly_18_regular.h ./bookerly_18_bold.h ./bookerly_18_bolditalic.h ./bookerly_18_italic.h))"
echo "#define BOOKERLY_20_FONT_ID ($(font_id ./bookerly_20_regular.h ./bookerly_20_bold.h ./bookerly_20_bolditalic.h ./bookerly_20_italic.h))"
echo "#define BOOKERLY_22_FONT_ID ($(font_id ./bookerly_22_regular.h ./bookerly_22_bold.h ./bookerly_22_bolditalic.h ./bookerly_22_italic.h))"
echo "#define LEXEND_14_FONT_ID ($(font_id ./lexend_14_regular.h ./lexend_14_bold.h ./lexend_14_regular.h ./lexend_14_bold.h))"
echo "#define LEXEND_16_FONT_ID ($(font_id ./lexend_16_regular.h ./lexend_16_bold.h ./lexend_16_regular.h ./lexend_16_bold.h))"
echo "#define LEXEND_18_FONT_ID ($(font_id ./lexend_18_regular.h ./lexend_18_bold.h ./lexend_18_regular.h ./lexend_18_bold.h))"
echo "#define LEXEND_20_FONT_ID ($(font_id ./lexend_20_regular.h ./lexend_20_bold.h ./lexend_20_regular.h ./lexend_20_bold.h))"
echo "#define LEXEND_22_FONT_ID ($(font_id ./lexend_22_regular.h ./lexend_22_bold.h ./lexend_22_regular.h ./lexend_22_bold.h))"
echo "#define NOTOSANS_14_FONT_ID ($(font_id ./notosans_14_regular.h ./notosans_14_bold.h ./notosans_14_bolditalic.h ./notosans_14_italic.h))"
echo "#define NOTOSANS_16_FONT_ID ($(font_id ./notosans_16_regular.h ./notosans_16_bold.h ./notosans_16_bolditalic.h ./notosans_16_italic.h))"
echo "#define NOTOSANS_18_FONT_ID ($(font_id ./notosans_18_regular.h ./notosans_18_bold.h ./notosans_18_bolditalic.h ./notosans_18_italic.h))"
echo "#define NOTOSANS_20_FONT_ID ($(font_id ./notosans_20_regular.h ./notosans_20_bold.h ./notosans_20_bolditalic.h ./notosans_20_italic.h))"
echo "#define NOTOSANS_22_FONT_ID ($(font_id ./notosans_22_regular.h ./notosans_22_bold.h ./notosans_22_bolditalic.h ./notosans_22_italic.h))"
echo "#define UI_10_FONT_ID ($(font_id ./ubuntu_10_regular.h ./ubuntu_10_bold.h))"
echo "#define UI_12_FONT_ID ($(font_id ./ubuntu_12_regular.h ./ubuntu_12_bold.h))"
echo "#define SMALL_FONT_ID ($(font_id ./notosans_8_regular.h))"
