#pragma once

#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_bolditalic.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/bookerly_20_bold.h>
#include <builtinFonts/bookerly_20_bolditalic.h>
#include <builtinFonts/bookerly_20_italic.h>
#include <builtinFonts/bookerly_20_regular.h>
#include <builtinFonts/bookerly_22_bold.h>
#include <builtinFonts/bookerly_22_bolditalic.h>
#include <builtinFonts/bookerly_22_italic.h>
#include <builtinFonts/bookerly_22_regular.h>
#include <builtinFonts/lexend_14_bold.h>
#include <builtinFonts/lexend_14_regular.h>
#include <builtinFonts/lexend_16_bold.h>
#include <builtinFonts/lexend_16_regular.h>
#include <builtinFonts/lexend_18_bold.h>
#include <builtinFonts/lexend_18_regular.h>
#include <builtinFonts/lexend_20_bold.h>
#include <builtinFonts/lexend_20_regular.h>
#include <builtinFonts/lexend_22_bold.h>
#include <builtinFonts/lexend_22_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_10_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/notosans_20_bold.h>
#include <builtinFonts/notosans_20_bolditalic.h>
#include <builtinFonts/notosans_20_italic.h>
#include <builtinFonts/notosans_20_regular.h>
#include <builtinFonts/notosans_22_bold.h>
#include <builtinFonts/notosans_22_bolditalic.h>
#include <builtinFonts/notosans_22_italic.h>
#include <builtinFonts/notosans_22_regular.h>
#include <builtinFonts/ubuntu_14_bold.h>
#include <builtinFonts/ubuntu_14_regular.h>
#include <builtinFonts/ubuntu_16_bold.h>
#include <builtinFonts/ubuntu_16_regular.h>
